"""Granada: geometria exacta y topologia de cupulas de mocarabes.

El nucleo aritmetico, las caras del teselado y la representacion topologica de
niveles estan activos. Los modulos de coronas y perfil unico se conservan como
referencia obsoleta. Ver PROXIMOS-PASOS.md.
"""

from granada.adaraja import (
    PESO_CIRCULO,
    PESO_PARABOLA,
    TIRO_CUENCO,
    TIRO_RECTO,
    PerfilArco,
    PuntoMalla,
    malla_adaraja,
    numeric_embedding_punto,
)
from granada.caras import (
    CONTORNO,
    Cara,
    FiguraPlana,
    GrafoNoAdmisible,
    PLANTILLAS,
    Plantilla,
    ResultadoCaras,
    Vecindad,
    ajuste_a_plantilla,
    clasificar,
    cruces_de_aristas,
    extraer_caras,
    tolerancia_por_resolucion,
)
from granada.celda import (
    Celda,
    anillo,
    cuna,
    numeric_embedding_celda,
    pasos_maximos,
    rombo,
    trapecio,
)
from granada.estratificacion import (
    HILADAS_MEDIDAS,
    RAZON_MEDIDA,
    Estratificacion,
    numeric_embedding_hilada,
)
from granada.niveles import (
    AsignacionNivel,
    InconsistenciaNiveles,
    RelacionVecindad,
    RestriccionNivel,
    RestriccionSinFirmar,
    ResultadoNiveles,
    TopologiaAscenso,
    TipoMocarabe,
    resolver_desde_vecindades,
    resolver_niveles,
    restricciones_firmadas,
)
from granada.cyclotomic import (
    CyclotomicInteger,
    CyclotomicRing,
    RealCyclotomicInteger,
    cyclotomic_polynomial,
    divisors,
    euler_phi,
    numeric_embedding_value,
    numeric_embedding_xy,
    poly_add,
    poly_divide_exact,
    poly_mul,
    poly_sub,
    poly_trim,
    solve_integer_linear,
    solve_rational_linear,
)

__version__ = "0.1.0"

__all__ = [
    "Cara",
    "Celda",
    "FiguraPlana",
    "GrafoNoAdmisible",
    "PerfilArco",
    "PLANTILLAS",
    "Plantilla",
    "PuntoMalla",
    "PESO_CIRCULO",
    "PESO_PARABOLA",
    "TIRO_CUENCO",
    "TIRO_RECTO",
    "Estratificacion",
    "ResultadoCaras",
    "Vecindad",
    "AsignacionNivel",
    "CONTORNO",
    "RelacionVecindad",
    "RestriccionSinFirmar",
    "InconsistenciaNiveles",
    "RestriccionNivel",
    "ResultadoNiveles",
    "TopologiaAscenso",
    "TipoMocarabe",
    "HILADAS_MEDIDAS",
    "RAZON_MEDIDA",
    "CyclotomicInteger",
    "CyclotomicRing",
    "RealCyclotomicInteger",
    "ajuste_a_plantilla",
    "anillo",
    "clasificar",
    "cruces_de_aristas",
    "cuna",
    "extraer_caras",
    "cyclotomic_polynomial",
    "divisors",
    "euler_phi",
    "malla_adaraja",
    "numeric_embedding_celda",
    "numeric_embedding_hilada",
    "numeric_embedding_punto",
    "numeric_embedding_value",
    "numeric_embedding_xy",
    "pasos_maximos",
    "poly_add",
    "poly_divide_exact",
    "poly_mul",
    "poly_sub",
    "poly_trim",
    "rombo",
    "resolver_desde_vecindades",
    "resolver_niveles",
    "restricciones_firmadas",
    "tolerancia_por_resolucion",
    "solve_integer_linear",
    "solve_rational_linear",
    "trapecio",
    "__version__",
]
