"""Granada: geometria exacta y topologia de cupulas de mocarabes.

El nucleo aritmetico, las caras del teselado, la representacion topologica de
niveles, la plantilla de doble perfil y el levantado de la malla estan activos.
Los modelos refutados -coronas polares, trapecio y perfil unico- se han retirado
(decision 0011); de aquel modulo solo queda la conica racional, como
interpolador. Ver PROXIMOS-PASOS.md.
"""

from granada.conica import (
    PESO_CIRCULO,
    PESO_PARABOLA,
    TIRO_CUENCO,
    TIRO_RECTO,
    PerfilArco,
)
from granada.caras import (
    CONTORNO,
    Cara,
    FiguraPlana,
    GrafoNoAdmisible,
    PLANTILLAS,
    Plantilla,
    ResultadoCaras,
    Vecindad,
    ajuste_a_plantilla,
    clasificar,
    cruces_de_aristas,
    extraer_caras,
    tolerancia_por_resolucion,
)
from granada.celda import (
    Celda,
    anillo,
    cuna,
    numeric_embedding_celda,
    pasos_maximos,
    rombo,
)
from granada.malla import (
    Malla,
    contiene_el_eje,
    corona,
    cupula,
    pieza,
    triangular,
)
from granada.perfil import (
    CIMA_MAYOR,
    CIMA_MENOR,
    MAYOR,
    MENOR,
    UNIDADES_ENTRE_NIVELES,
    PlantillaPerfil,
    paralelas,
    vecindades_no_paralelas,
)
from granada.niveles import (
    AsignacionNivel,
    InconsistenciaNiveles,
    RelacionVecindad,
    RestriccionNivel,
    RestriccionSinFirmar,
    ResultadoNiveles,
    TopologiaAscenso,
    TipoMocarabe,
    resolver_desde_vecindades,
    resolver_niveles,
    restricciones_firmadas,
)
from granada.cyclotomic import (
    CyclotomicInteger,
    CyclotomicRing,
    RealCyclotomicInteger,
    cyclotomic_polynomial,
    divisors,
    euler_phi,
    numeric_embedding_value,
    numeric_embedding_xy,
    poly_add,
    poly_divide_exact,
    poly_mul,
    poly_sub,
    poly_trim,
    solve_integer_linear,
    solve_rational_linear,
)

__version__ = "0.1.0"

__all__ = [
    "Cara",
    "Celda",
    "FiguraPlana",
    "GrafoNoAdmisible",
    "PerfilArco",
    "PlantillaPerfil",
    "Malla",
    "PLANTILLAS",
    "Plantilla",
    "PESO_CIRCULO",
    "PESO_PARABOLA",
    "TIRO_CUENCO",
    "TIRO_RECTO",
    "ResultadoCaras",
    "Vecindad",
    "AsignacionNivel",
    "CONTORNO",
    "RelacionVecindad",
    "RestriccionSinFirmar",
    "InconsistenciaNiveles",
    "RestriccionNivel",
    "ResultadoNiveles",
    "TopologiaAscenso",
    "TipoMocarabe",
    "CIMA_MAYOR",
    "CIMA_MENOR",
    "MAYOR",
    "MENOR",
    "UNIDADES_ENTRE_NIVELES",
    "CyclotomicInteger",
    "CyclotomicRing",
    "RealCyclotomicInteger",
    "ajuste_a_plantilla",
    "anillo",
    "clasificar",
    "cruces_de_aristas",
    "contiene_el_eje",
    "corona",
    "cuna",
    "cupula",
    "extraer_caras",
    "cyclotomic_polynomial",
    "divisors",
    "euler_phi",
    "numeric_embedding_celda",
    "numeric_embedding_value",
    "numeric_embedding_xy",
    "pasos_maximos",
    "pieza",
    "poly_add",
    "poly_divide_exact",
    "poly_mul",
    "poly_sub",
    "poly_trim",
    "paralelas",
    "rombo",
    "resolver_desde_vecindades",
    "resolver_niveles",
    "restricciones_firmadas",
    "triangular",
    "vecindades_no_paralelas",
    "tolerancia_por_resolucion",
    "solve_integer_linear",
    "solve_rational_linear",
    "__version__",
]
